"""Is each run still the output of the code and data it recorded? (SPEC §8)

A run is compared against the working tree by content hash -- no git needed:

* each recorded code unit is re-hashed semantically (comment/docstring edits are
  *cosmetic* and never make a run stale);
* each input is re-hashed (through the size/mtime cache);
* an input that is another run's artifact ties the two runs together: if the
  producer re-ran and its artifact changed, the consumer is stale; if the
  producer is stale, the consumer is *upstream-stale*;
* artifacts on disk that no longer match their recorded hash are *tampered*.

A person can accept a staleness they have reviewed (``vouch accept``). The
acceptance names the exact current hashes, so the next edit re-opens it.
"""

from __future__ import annotations

import dataclasses
import datetime as _dt
import getpass
import json
import subprocess
from pathlib import Path
from typing import Any

from .config import Config
from .hashing import HashCache, mode_of
from .units import raw_hash, units_from_file

ERROR_STATES = ("incomplete", "tampered", "stale", "upstream-stale")
LEDGER = "accepted.toml"


@dataclasses.dataclass
class Reason:
    kind: str          # unit-changed unit-missing file-missing unparseable input-changed
                       # input-regenerated upstream tampered absent-input absent-artifact
                       # env-drift cosmetic incomplete
    subject: str       # e.g. "src/models.py::score", "data/x.csv", run id
    detail: str = ""
    current: str | None = None      # current hash, what an acceptance records

    @property
    def token(self) -> str:
        """The ledger key for an acceptable reason."""
        return {"unit-changed": "unit", "unit-missing": "unit", "file-missing": "unit",
                "unparseable": "unit", "input-changed": "input",
                "input-regenerated": "regen"}.get(self.kind, self.kind) + ":" + self.subject


OWN_STALE = ("unit-changed", "unit-missing", "file-missing", "unparseable", "input-changed",
             "input-regenerated")


@dataclasses.dataclass
class RunState:
    run: str
    state: str                               # fresh cosmetic accepted stale upstream-stale
                                             # tampered incomplete
    reasons: list[Reason]
    command: str
    acceptance: dict | None = None
    recorded: dict | None = None

    def of(self, *kinds: str) -> list[Reason]:
        return [r for r in self.reasons if r.kind in kinds]

    @property
    def is_error(self) -> bool:
        return self.state in ERROR_STATES

    def summary(self) -> str:
        if self.state == "fresh":
            return "fresh"
        if self.state == "cosmetic":
            return "fresh (files changed, but not in anything this run executed)"
        if self.state == "accepted":
            a = self.acceptance or {}
            return f"accepted: {a.get('why', '')}".strip()
        if self.state == "incomplete":
            return "the run did not finish"
        if self.state == "upstream-stale":
            ups = sorted({r.subject for r in self.of("upstream")})
            return f"reads the output of stale run{'s' if len(ups) > 1 else ''} {', '.join(ups)}"
        if self.state == "tampered":
            return "artifact changed outside a run: " + ", ".join(r.subject for r in self.of("tampered"))
        parts = []
        units = [r.subject for r in self.of("unit-changed", "unit-missing", "file-missing",
                                              "unparseable")]
        if units:
            parts.append(_list(units) + " changed")
        ins = [r.subject for r in self.of("input-changed")]
        if ins:
            parts.append("input " + _list(ins) + " changed")
        regen = [r for r in self.of("input-regenerated")]
        if regen:
            parts.append("input " + _list([r.subject for r in regen]) + " was regenerated by "
                         + _list(sorted({r.detail for r in regen})))
        return "; ".join(parts) + " since the run"


def _list(items: list[str], n: int = 3) -> str:
    return ", ".join(items[:n]) + (f" (+{len(items) - n} more)" if len(items) > n else "")


# ---------------------------------------------------------------------------
# the accept ledger (.vouch/accepted.toml)
# ---------------------------------------------------------------------------

def load_ledger(cfg: Config) -> dict[str, dict]:
    path = cfg.store / LEDGER
    if not path.is_file():
        return {}
    import sys
    if sys.version_info >= (3, 11):
        import tomllib
    else:  # pragma: no cover
        import tomli as tomllib
    with open(path, "rb") as fh:
        data = tomllib.load(fh)
    return {e["run"]: e for e in data.get("accept", []) if "run" in e}


def _toml_str(s: str) -> str:
    return json.dumps(str(s), ensure_ascii=False)          # TOML basic strings match JSON's


def write_ledger(cfg: Config, entries: dict[str, dict]) -> None:
    lines = ["# Stale runs reviewed and accepted by hand (`vouch accept`). Each acceptance",
             "# clears its run only for the exact hashes listed; the next edit re-opens it.", ""]
    for run in sorted(entries):
        e = entries[run]
        lines += ["[[accept]]", f"run = {_toml_str(run)}", f"why = {_toml_str(e.get('why', ''))}",
                  f"by = {_toml_str(e.get('by', ''))}", f"date = {_toml_str(e.get('date', ''))}",
                  "[accept.hashes]"]
        lines += [f"{_toml_str(k)} = {_toml_str(v)}" for k, v in sorted(e.get("hashes", {}).items())]
        lines.append("")
    cfg.store.mkdir(parents=True, exist_ok=True)
    (cfg.store / LEDGER).write_text("\n".join(lines), encoding="utf-8", newline="\n")


def who() -> str:
    try:
        r = subprocess.run(["git", "config", "user.name"], capture_output=True, text=True, timeout=5)
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass
    try:
        return getpass.getuser()
    except Exception:  # pragma: no cover
        return "unknown"


def now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# assessment
# ---------------------------------------------------------------------------

class _Units:
    """Current unit hashes per file, parsed once per check."""

    def __init__(self, root: Path):
        self.root = root
        self.cache: dict[str, dict | None] = {}

    def of(self, rel: str) -> dict | None | str:
        if rel not in self.cache:
            p = self.root / rel
            if not p.is_file():
                self.cache[rel] = "missing"
            else:
                self.cache[rel] = units_from_file(p)
        return self.cache[rel]


def _env_drift(rec: dict) -> list[Reason]:
    out = []
    env = rec.get("env") or {}
    import platform
    rec_py = str(env.get("python", ""))
    cur_py = platform.python_version()
    if rec_py and rec_py.split(".")[:2] != cur_py.split(".")[:2]:
        out.append(Reason("env-drift", "python", f"recorded with Python {rec_py}, now {cur_py}"))
    from importlib import metadata
    for dist, ver in sorted((env.get("packages") or {}).items()):
        try:
            cur = metadata.version(dist)
        except metadata.PackageNotFoundError:
            cur = None
        if cur != ver:
            out.append(Reason("env-drift", dist,
                              f"{dist} {ver} when recorded, " + (f"{cur} now" if cur else "not installed now")))
    return out


def assess(cfg: Config, runs: dict[str, dict], *, cache: HashCache | None = None,
           ledger: dict[str, dict] | None = None, check_env: bool = True) -> dict[str, RunState]:
    """The freshness state of every run."""
    cache = cache or HashCache(cfg.store / "cache" / "hashes.json")
    ledger = load_ledger(cfg) if ledger is None else ledger
    units = _Units(cfg.root)

    producers: dict[str, tuple[str, str | None]] = {}
    for run, rec in runs.items():
        for path, a in (rec.get("artifacts") or {}).items():
            producers.setdefault(path, (run, a.get("hash")))

    own: dict[str, list[Reason]] = {}
    for run, rec in runs.items():
        reasons: list[Reason] = []
        if rec.get("status") != "complete":
            reasons.append(Reason("incomplete", run, f"status {rec.get('status')!r}"))

        # code
        by_file: dict[str, list[tuple[str, str]]] = {}
        for ukey, h in (rec.get("code", {}).get("units") or {}).items():
            path, _, qual = ukey.partition("::")
            by_file.setdefault(path, []).append((qual, h))
        for path, recorded in sorted(by_file.items()):
            current = units.of(path)
            if current == "missing":
                reasons.append(Reason("file-missing", path, "file deleted or moved", "missing"))
                continue
            if current is None:
                reasons.append(Reason("unparseable", path, "no longer parses", "unparseable"))
                continue
            for qual, h in recorded:
                now_h = current.get(qual)
                subject = f"{path}::{qual}"
                if now_h is None:
                    reasons.append(Reason("unit-missing", subject, "removed or renamed", "missing"))
                elif now_h != h:
                    reasons.append(Reason("unit-changed", subject, "", now_h))
        if not any(r.kind in ("unit-changed", "unit-missing", "file-missing", "unparseable")
                   for r in reasons):
            for path, rh in sorted((rec.get("code", {}).get("files") or {}).items()):
                cur = raw_hash(cfg.root / path)
                if cur is not None and cur != rh:
                    reasons.append(Reason("cosmetic", path, "changed outside the code this run used"))

        # inputs
        for path, h in sorted((rec.get("inputs") or {}).items()):
            prod = producers.get(path)
            if prod and prod[0] != run and h is not None and prod[1] is not None and prod[1] != h:
                reasons.append(Reason("input-regenerated", path, prod[0], prod[1]))
                continue
            p = cfg.root / path
            if not p.exists():
                reasons.append(Reason("absent-input", path, "not on disk; cannot re-hash"))
                continue
            if h is None:
                continue
            cur = cache.path_hash(p, mode_of(h))
            if cur != h:
                reasons.append(Reason("input-changed", path, "", cur))

        # artifacts on disk
        for path, a in sorted((rec.get("artifacts") or {}).items()):
            h = a.get("hash")
            p = cfg.root / path
            if not p.exists():
                reasons.append(Reason("absent-artifact", path, "not on disk"))
                continue
            if h is not None and cache.path_hash(p, mode_of(h)) != h:
                reasons.append(Reason("tampered", path, "differs from the hash the run recorded"))

        if check_env:
            reasons += _env_drift(rec)
        own[run] = reasons
    cache.save()

    # own state, then upstream propagation (consumers of stale producers)
    states: dict[str, RunState] = {}

    def own_state(run: str) -> RunState:
        rec = runs[run]
        reasons = own[run]
        cmd = " ".join(rec.get("command") or [])
        stale = [r for r in reasons if r.kind in OWN_STALE]
        acc = ledger.get(run)
        if any(r.kind == "incomplete" for r in reasons):
            st = "incomplete"
        elif any(r.kind == "tampered" for r in reasons):
            st = "tampered"
        elif stale:
            covered = acc is not None and all(
                (acc.get("hashes") or {}).get(r.token) == (r.current or "") for r in stale)
            st = "accepted" if covered else "stale"
        elif any(r.kind == "cosmetic" for r in reasons):
            st = "cosmetic"
        else:
            st = "fresh"
        return RunState(run, st, list(reasons), cmd, acc if st == "accepted" else None, rec)

    for run in runs:
        states[run] = own_state(run)

    deps: dict[str, set[str]] = {}          # run -> the runs whose artifacts it reads
    for run, rec in runs.items():
        for path in (rec.get("inputs") or {}):
            prod = producers.get(path)
            if prod and prod[0] != run:
                deps.setdefault(run, set()).add(prod[0])

    def upstream(run: str, seen: frozenset) -> list[str]:
        bad = []
        for dep in sorted(deps.get(run, ())):
            if dep in seen:
                continue
            ds = states[dep]
            if ds.state in ("stale", "tampered", "incomplete") or upstream(dep, seen | {dep}):
                bad.append(dep)
        return bad

    for run, st in states.items():
        if st.state in ("fresh", "cosmetic", "accepted"):
            bad = upstream(run, frozenset({run}))
            if bad:
                st.reasons += [Reason("upstream", dep, states[dep].state) for dep in bad]
                st.state = "upstream-stale"
    return states


def acceptable_hashes(state: RunState) -> dict[str, str]:
    """What ``vouch accept`` records for a stale run: every own stale reason, as of now."""
    return {r.token: r.current or "" for r in state.reasons if r.kind in OWN_STALE}


def state_word(st: RunState | None) -> str:
    return st.state if st is not None else "-"
