"""Writing the generated LaTeX: the values file and table bodies (SPEC §7.6, §5.4).

Every string here is built from raw-string templates. Never route LaTeX through
non-raw Python literals: ``\\v``, ``\\t``, ``\\b``, ``\\f`` and ``\\a`` are escape
sequences and silently rewrite the document (asqc lesson, SPEC §18).
"""

from __future__ import annotations

import unicodedata

VALUES_HEADER = (r"% vouch-values.tex -- GENERATED by `vouch build`. Do not edit: "
                 r"`vouch check` detects edits.")

_TIP_UNICODE = str.maketrans({"±": "+/-", "→": "->", "·": "|", "…": "...", "×": "x",
                              "—": "--", "–": "-", "≤": "<=", "≥": ">=", "’": "'",
                              "“": '"', "”": '"'})
_TIP_ESCAPES = {"\\": "/", "{": "(", "}": ")", "%": r"\%", "#": r"\#", "$": r"\$",
                "&": r"\&", "_": r"\_", "^": r"\textasciicircum{}", "~": r"\textasciitilde{}"}
TIP_NEWLINE = r"\textCR "


def tip_escape(text: str) -> str:
    """Plain text made safe for a PDF tooltip (it goes through hyperref's \\pdfstringdef)."""
    text = str(text).translate(_TIP_UNICODE)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    return "".join(_TIP_ESCAPES.get(c, c) for c in " ".join(text.split()))


def tooltip(lines: list[str]) -> str:
    return TIP_NEWLINE.join(tip_escape(ln) for ln in lines if ln)


def set_line(key: str, fmt: str, rendered: str, plain: str, tip: str, changed: bool) -> str:
    return (r"\vouch@set{" + key + "}{" + fmt + "}{" + rendered + "}{" + plain + "}{" + tip
            + "}{" + ("1" if changed else "0") + "}")


def raw_line(key: str, raw: str) -> str:
    return r"\vouch@raw{" + key + "}{" + raw + "}"


def claim_line(key: str, holds: bool, tip: str, changed: bool) -> str:
    return (r"\vouch@claim{" + key + "}{" + ("1" if holds else "0") + "}{" + tip + "}{"
            + ("1" if changed else "0") + "}")


def prov_line(key: str, latex: str) -> str:
    """The key's entry in the provenance appendix (typeset LaTeX, already escaped)."""
    return r"\vouch@prov{" + key + "}{" + latex + "}"


def pending_line(key: str, producer: str) -> str:
    return r"\vouch@pending{" + key + "}{" + tip_escape(producer) + "}"


def table_line(key: str, path: str) -> str:
    return r"\vouch@table{" + key + "}{" + path + "}"


def state_line(run: str, text: str) -> str:
    """A run's freshness, read by tooltips through \\vouch@runstate. Kept on its own
    line because it depends on the working tree, not on what was recorded."""
    return r"\vouch@state{" + run + "}{" + text + "}"


def values_file(lines: list[str], summary: str) -> str:
    return "\n".join([VALUES_HEADER, "% " + summary, *lines, ""])


def best_cell(inner: str) -> str:
    return r"\vouchbest{" + inner + "}"


def second_cell(inner: str) -> str:
    return r"\vouchsecond{" + inner + "}"


def cite(key: str) -> str:
    return r"\vouch{" + key + "}"


def table_body(header: str, rows: list[list[str]], midrules: list[int]) -> str:
    out = ["% " + header]
    for i, cells in enumerate(rows, start=1):
        out.append(" & ".join(cells) + r" \\")
        if i in midrules and i < len(rows):
            out.append(r"\midrule")
    return "\n".join(out) + "\n"
